### ISSUE TITLE
charlist not working

### ISSUE THREAD

**Issue by lazenes** [erdem1999erdem/NFSToolHB#5]
We want to add the Turkish alphabet to the game, but even though we edit char_list.txt, in-game texts are corrupted.
![image](https://github.com/erdem1999erdem/NFSToolHB/assets/18098025/8ef00e59-1cb3-442e-a507-5129b88ce9ed)
![image](https://github.com/erdem1999erdem/NFSToolHB/assets/18098025/0145a258-ad3a-41fd-b77c-255e54750e56)
![image](https://github.com/erdem1999erdem/NFSToolHB/assets/18098025/610fef4d-45bd-4392-a073-7ac24e22503e)

**Comment by HarGabt** [comment]
@lazenes 
From what I can see, the charslist and its encoding are "hardcoded" into the program itself, meaning that the source code will have to be changed a bit to be able to digest other symbols than it can right now.


I have made some changes in program's code and made a new histogram that should fit your needs.
Try using [this test build along with a new histogram](https://github.com/erdem1999erdem/NFSToolHB/files/13324656/test.zip) during `BinaryChunk` compilation and report if it works. If it does, I'll make a pull request to the repository.
Additionally, you can share your localisation files here so we can take a look at things that may or may not work and troubleshoot if needed.

**Comment by Punpude** [comment]
https://github.com/erdem1999erdem/NFSToolHB/releases/download/nfstoolhb/NFSLocaleToolHBwithUI1.3.exe
[Chars_list.txt](https://github.com/erdem1999erdem/NFSToolHB/files/13382498/Chars_list.txt)
