### ISSUE TITLE
Some glyphs doesn't show up correctly.

### ISSUE THREAD

**Issue by memaybeogaming69** [erdem1999erdem/NFSToolHB#7]
Hello, I'm trying to translate Battlefield 4 to Vietnamese but some glyphs doesn't show up correctly, idk about programming lol so I hope you can help me. Thanks. 
![image](https://github.com/erdem1999erdem/NFSToolHB/assets/159686484/d6f11819-382f-4770-b748-738c96b02972)
![image](https://github.com/erdem1999erdem/NFSToolHB/assets/159686484/d3b4553a-4354-41fb-a511-44c1805724f3)
The sentence in the first image is "GIỚI THIỆU" and the second one is "Trời ơi, tôi không muốn chết cùng với bài này"
This is the chars list I used: 
[Chars_list.txt](https://github.com/erdem1999erdem/NFSToolHB/files/14231789/Chars_list.txt)

**Comment by memaybeogaming69** [comment]
I know this tool is for Need for Speed but the histogram thing maybe works with other games aswell?

**Comment by HarGabt** [comment]
Can you please provide all of your files of your localization project? We need it for testing the tool in order to find out if it is the issue with its code itself or its probable improper use.

**Comment by memaybeogaming69** [comment]
> Can you please provide all of your files of your localization project? We need it for testing the tool in order to find out if it is the issue with its code itself or its probable improper use.

[bf4.zip](https://github.com/erdem1999erdem/NFSToolHB/files/14235775/bf4.zip)

**Comment by Punpude** [comment]
![image](https://github.com/erdem1999erdem/NFSToolHB/assets/63004776/de11e772-a7ac-4dd5-b30d-d449fe26a172)
chars limit only 127
The original has 43 + your 128. 
Therefore 43 characters are not included in this histogram.

**Comment by memaybeogaming69** [comment]
there is no way to add more characters?

**Comment by memaybeogaming69** [comment]
there is no way to add more characters? And I have another question, is it possible to use histogram from other languages like Chinese to add the characters from my language? Like I guess it has more characters so it might works.
